# Generated by Django 5.0.9 on 2024-12-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SectionContent',
            new_name='ContentSection',
        ),
    ]
