# Generated by Django 5.0.9 on 2024-12-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_rename_sectioncontent_contentsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentsection',
            options={'ordering': ['id'], 'verbose_name': 'ContentSection', 'verbose_name_plural': 'ContentSection'},
        ),
    ]
