# Generated by Django 5.0.9 on 2024-12-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_rename_contentsection_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['id'], 'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
    ]
