# Generated by Django 5.0.9 on 2024-12-26 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_alter_content_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Test description')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Question')),
                ('answer', models.TextField(blank=True, max_length=40, null=True, verbose_name='Answer')),
                ('test_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.section', verbose_name='Test section')),
            ],
            options={
                'verbose_name': 'Tests',
                'verbose_name_plural': 'Tests',
                'ordering': ['test_section'],
            },
        ),
    ]
